### PR TITLE
Add get cohorts method and test

### PR DESCRIPTION
**Pull request by s-espinosa**
@srt32 Believe this implements the method that we discussed. Let me know what you think!

### CODE REVIEW

**Comment by srt32** [comment]
Fantastic! Were you able to sanity check it worked locally?

Please follow the instructions in https://github.com/turingschool-projects/omniauth-census#releasing-a-new-version once you merge and lemme know if you have any issues!

**Comment by s-espinosa** [comment]
Hmmm... I'm actually having trouble sanity checking this, but believe it's an issue with another part of the gem. Going to go ahead and merge/bump version.

Question for you: when you initialize a new Census::Client we have hard coded that the scope is admin. That feels wonky. One of the errors that I've gotten trying to validate is that I have an invalid scope. Taking that line out allows me to initialize a new client, but then not hit this endpoint.

I don't think I like the idea that every Census::Client initializes looking for an admin scope, and I don't think I like the idea of a Census::Client implementing methods that we know it can't actually use. It seems like maybe we should have a Census::AdminClient and a Census::DefaultClient?

I could see an issue where this leads to classes multiplying moving forward as different scopes are supported, so definitely open to other thoughts. Better to just have the methods on Census::Client and raise an error if a user tries to use one they don't have access to?

**Comment by srt32** [comment]
You should be fine with admin scope if your user in census has the admin
role and the oauth app you made has the admin role on it. Need better docs
here :)

Is there not a way to override the scope on client creation?

**Comment by s-espinosa** [comment]
Not that I see? [link](https://github.com/turingschool-projects/omniauth-census/blob/master/lib/census/client.rb#L26)

Didn't realize that the OAuth app needed the same piece. Thanks!

**Pull request merged**
